name: hospital_maraba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  hive: ^2.0.5
  qr_flutter: ^4.0.0
  firebase_auth: ^3.3.6 
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.11
  mask_text_input_formatter: 2.3.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  freezed_annotation: ^1.1.0
  json_annotation: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  freezed: ^1.1.1
  json_serializable: any
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/realLogo.jpg
    - assets/images/cj.png
