name: hospital_maraba
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  jiffy: ^5.0.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hive: ^2.0.5
  qr_flutter: ^4.0.0
  firebase_auth: ^4.1.0 
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  mask_text_input_formatter: ^2.4.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  freezed_annotation: ^2.2.0
  json_annotation: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: ^2.0.1
  freezed: ^2.2.1
  json_serializable: any
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/realLogo.jpg
    - assets/images/cj.png
    - assets/images/logo.png