// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPhMYKVDuUY4YtiDF4S9Kfp0o-6XQ0w0',
    appId: '1:961961820221:web:1dd51b99ea2c6398d0aa54',
    messagingSenderId: '961961820221',
    projectId: 'agendamentos-maraba',
    authDomain: 'agendamentos-maraba.firebaseapp.com',
    storageBucket: 'agendamentos-maraba.appspot.com',
    measurementId: 'G-48KZQR9BT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYthF_xejcwTfbFkSnOQ-c9Div0jjypc',
    appId: '1:961961820221:android:05b6ae10f742a8c2d0aa54',
    messagingSenderId: '961961820221',
    projectId: 'agendamentos-maraba',
    storageBucket: 'agendamentos-maraba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1rhRqtmsNRUTO0c6QSrCRxeBnpWP_Mw',
    appId: '1:961961820221:ios:229ce138be10b0fbd0aa54',
    messagingSenderId: '961961820221',
    projectId: 'agendamentos-maraba',
    storageBucket: 'agendamentos-maraba.appspot.com',
    iosClientId: '961961820221-04o93fk68r8scoe2mevdallhioulu20o.apps.googleusercontent.com',
    iosBundleId: 'dev.snst.hospital-maraba',
  );
}
